.\" Copyright (c) 2010 Philippe Pepiot <phil@philpep.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.\"
.Dd $Mdocdate: March 25 2010 $
.Dt HTTPD.CONF 5
.Os
.Sh NAME
.Nm httpd.conf
.Nd httpd configuration file
.Sh DESCRIPTION
.Nm
is the configuration file for the HTTP daemon
.Xr httpd 8 .
.Pp
Comments can be put anywhere in the file using a hash mark
.Pq # ,
and extend to the end of the current line.
.Bl -tag -width Ds
.It Xo
.Ic listen
.Op Ic on Ar interface
.Op Ic port Ar port
.Xc
Specify an
.Ar interface
and
.Ar port
to listen on.
An IP address or domain name may be used in place of
.Ar interface.
.Pp
.It Xo
.Ic host hostname root directory
.Xc
Serve virtualhost
.Ar hostname
with files in
.Ar directory
.El
.Sh EXAMPLES
.Pp
.Bd -literal -offset indent
listen on lo0
host www.example.com root /var/www/example.com/
host www.foo.net root /var/www/foo/
.Ed
.Sh SEE ALSO
.Xr httpd 8
.Xr services 5
